services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estagio-teste-backend-api
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: marcus13
      DB_HOST: estagio-teste-backend-mysql
      DB_DATABASE: teste_backend_estagio
      DB_USERNAME: root
      DB_PASSWORD: marcus13
    command: sh -c "composer install && docker-compose run --rm api composer migrate && php -S 0.0.0.0:8080 -t public"

  mysql:
    image: mysql:8.0
    container_name: estagio-teste-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: marcus13
      MYSQL_DATABASE: teste_backend_estagio

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
