services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contato-seguro
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    command: sh -c "composer install && php -S 0.0.0.0:8000 -t public"
