services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estagio-teste-backend-api
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${MYSQL_HOST}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: sh -c "composer install && php -S 0.0.0.0:8080 -t public"

  mysql:
    image: mysql:8.0
    container_name: estagio-teste-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
