services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estagio-teste-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    command: sh -c "composer install && php artisan migrate && php -S 0.0.0.0:8000 -t public"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
